<?php

namespace RoBYCoNTe\FilamentFlow\Tests\Fixtures\Resources;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables;
use Filament\Tables\Table;
use RoBYCoNTe\FilamentFlow\Concerns\HasWorkflowCreation;
use RoBYCoNTe\FilamentFlow\Tests\Fixtures\Models\Order;
use RoBYCoNTe\FilamentFlow\Tests\Fixtures\Resources\OrderResource\Pages;

class OrderResource extends Resource
{
    use HasWorkflowCreation;

    protected static ?string $model = Order::class;

    protected static string|null|\BackedEnum $navigationIcon = Heroicon::OutlinedShoppingBag;

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Informazioni Ordine')->schema([
                TextInput::make('order_number')->required(),
                TextInput::make('customer_name')->required(),
                TextInput::make('customer_email')->email(),
                TextInput::make('total_amount')->numeric()->required(),
            ]),
            Section::make('Note')->schema([
                Textarea::make('notes'),
                Textarea::make('processing_notes'),
                Textarea::make('shipping_notes'),
            ]),
            Section::make('Spedizione')->schema([
                TextInput::make('tracking_number'),
                TextInput::make('carrier'),
                DatePicker::make('estimated_delivery'),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('order_number')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('customer_name')->searchable(),
                Tables\Columns\TextColumn::make('total_amount')->money('EUR'),
                Tables\Columns\TextColumn::make('state')->badge(),
                Tables\Columns\TextColumn::make('notes'),
                Tables\Columns\TextColumn::make('tracking_number'),
                Tables\Columns\TextColumn::make('carrier'),
            ])
            ->actions([
                // StateActionGroup will be generated by workflow
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListOrders::route('/'),
            'create' => Pages\CreateOrder::route('/create'),
            'edit' => Pages\EditOrder::route('/{record}/edit'),
        ];
    }
}
